 
-- 계절성 지수 산출 (2014~2016년, 주차별)

SELECT
    A.REGIONID
    , A.PRODUCT
    , A.YEARWEEK
    , A.WEEK
    , A.QTY
    , B.AVERAGE
    , ROUND(A.QTY/B.AVERAGE,1) AS RATIO
FROM(
    SELECT
        REGIONID
        , PRODUCT
        , YEARWEEK
        , SUBSTR(YEARWEEK,5,6) AS WEEK
        , QTY
    FROM KOPO_CHANNEL_SEASONALITY_NEW
        WHERE REGIONID = 'A01'
        AND SUBSTR(YEARWEEK,5,6) NOT IN ('53')
        AND PRODUCT = 'PRODUCT1'
        ORDER BY WEEK, YEARWEEK) A
LEFT JOIN(
    SELECT
        REGIONID
        , PRODUCT
        , SUBSTR(YEARWEEK,5,6) AS WEEK
        , ROUND(AVG(QTY),1) AS AVERAGE
    FROM(
        SELECT *
        FROM KOPO_CHANNEL_SEASONALITY_NEW
        WHERE REGIONID = 'A01'
        AND SUBSTR(YEARWEEK,5,6) NOT IN ('53')
        AND PRODUCT = 'PRODUCT1'
        )
    GROUP BY REGIONID, PRODUCT, SUBSTR(YEARWEEK,5,6)
    ORDER BY SUBSTR(YEARWEEK,5,6)) B
ON A.WEEK = B.WEEK;



-- 테이블 A

SELECT
    REGIONID
    , PRODUCT
    , YEARWEEK
    , SUBSTR(YEARWEEK,5,6) AS WEEK
    , QTY
FROM KOPO_CHANNEL_SEASONALITY_NEW
    WHERE REGIONID = 'A01'
    AND SUBSTR(YEARWEEK,5,6) NOT IN ('53')
    AND PRODUCT = 'PRODUCT1'
    ORDER BY WEEK, YEARWEEK;


-- 테이블 B

SELECT
    REGIONID
    , PRODUCT
    , SUBSTR(YEARWEEK,5,6) AS WEEK
    , ROUND(AVG(QTY),1) AS AVERAGE
FROM(
    SELECT *
    FROM KOPO_CHANNEL_SEASONALITY_NEW
    WHERE REGIONID = 'A01'
    AND SUBSTR(YEARWEEK,5,6) NOT IN ('53')
    AND PRODUCT = 'PRODUCT1'
    )
GROUP BY REGIONID, PRODUCT, SUBSTR(YEARWEEK,5,6)
ORDER BY SUBSTR(YEARWEEK,5,6);


SELECT * FROM KOPO_PARAMETER_HK;

SELECT * FROM DT_RESULT_FINAL2;