create table DEPT (
    dept_no varchar2(10),
    dept varchar2(10),
    name varchar2(10)
);

CREATE TABLE BOSS (
    DEPT_NO VARCHAR2(10),
    BOSS VARCHAR2(10),
    LOCATION VARCHAR2(10)
);

EDIT DEPT;

EDIT BOSS;

SELECT * FROM DEPT;

SELECT * FROM BOSS;

SELECT * FROM DEPT A
LEFT JOIN
BOSS B
ON A.DEPT_NO = B.DEPT_NO;

SELECT * FROM BOSS A
LEFT JOIN
DEPT B
ON A.DEPT_NO = B.DEPT_NO;


SELECT * FROM DEPT A
RIGHT JOIN
BOSS B
ON A.DEPT_NO = B.DEPT_NO;

SELECT * FROM BOSS A
RIGHT JOIN
DEPT B
ON A.DEPT_NO = B.DEPT_NO;


SELECT *
FROM (SELECT * FROM DEPT 
WHERE DEPT_NO = 1
OR DEPT_NO=2) A
LEFT JOIN
BOSS B
ON A.DEPT_NO = B.DEPT_NO;

-- 대/소문자 변경하기
SELECT 
   UPPER(PRODUCT) AS CASE1,
   LOWER(PRODUCT) AS CASE2
FROM KOPO_CHANNEL_SEASONALITY_NEW;

SELECT 
    CONCAT(REGIONID,CONCAT('_',PRODUCT)) AS KEYCOL1,
    REGIONID||'_'||PRODUCT AS KEYCOL2
FROM KOPO_CHANNEL_SEASONALITY_NEW;

SELECT 
    PRODUCT,
    SUBSTR(PRODUCT,1,7)
FROM KOPO_CHANNEL_SEASONALITY_NEW;

SELECT 
RPAD(PRODUCT, 10, '0')
FROM KOPO_CHANNEL_SEASONALITY_NEW;

SELECT 
PRODUCT,
    LTRIM(PRODUCT,'PRO'),
    RTRIM(PRODUCT, '56')
FROM KOPO_CHANNEL_SEASONALITY_NEW;

SELECT LENGTH(TRIM('   ABC    ')) FROM DUAL;



SELECT A.*,
CASE WHEN PREDICTION_QTY =0
    THEN 0
    ELSE 1-ABS(PREDICTION_QTY-REAL_QTY)/PREDICTION_QTY END AS ACCURACY
FROM DT_RESULT_FINAL3 A;



    
    
SELECT
REGIONID, ITEM, TARGETWEEK, PLANWEEK, IR, PRODUCT,
PMAP,
MAP_PRICE,
CASE WHEN MAP_PRICE = 0 -- (pmap / map_price ratio의 제수(map_price)가 0일 때의 예외처리를 위함
    THEN 1
    ELSE PMAP/NVL(MAP_PRICE,1) END AS PROMOTION_RATIO  -- NVL(a,b) => a값이 null이면 b로 대체하라
FROM KOPO_PROMOTION;


SELECT *
    FROM (
        SELECT
            REGIONID
            ,SUBSTR(YEARWEEK,5,6) AS WEEK
            ,ROUND(AVG(QTY),0) AS AVG_QTY
        FROM KOPO_CHANNEL_SEASONALITY_NEW
    GROUP BY REGIONID, SUBSTR(YEARWEEK,5,6)
    ORDER BY REGIONID, SUBSTR(YEARWEEK,5,6)
    )
    PIVOT (
    AVG(AVG_QTY)
    --SUM(AVG_QTY)
    FOR WEEK IN ('01' W01, '02' W02, '03' W03, '04' W04, '05' W05, '06' W06)
    )
    ORDER BY REGIONID, PRODUCT;
    
    
SELECT
            REGIONID
            ,SUBSTR(YEARWEEK,5,6) AS WEEK
            ,ROUND(AVG(QTY),0) AS AVG_QTY
        FROM KOPO_CHANNEL_SEASONALITY_NEW
    GROUP BY REGIONID, SUBSTR(YEARWEEK,5,6)
    ORDER BY REGIONID, SUBSTR(YEARWEEK,5,6);
    
    
SELECT * FROM KOPO_CHANNEL_SEASONALITY_NEW;


SELECT  *
        FROM DT_RESULT_FINAL2;

SELECT 
    *
     FROM (
        SELECT  *
        FROM DT_RESULT_FINAL2
)
PIVOT( 
    SUM(SALES)
    FOR MEASURE IN 
   ('REAL-QTY' AS REAL_QTY,'PREDICTION-QTY' AS PREDICTION_QTY)
)
ORDER BY PRODUCTGROUP, PRODUCT, ITEM, YEARWEEK;


SELECT
    REPLACE(LPAD(CUSTOMERCODE, 10, '0')
    ,SUBSTR(CUSTOMERCODE, -4), '****')
    AS CUSTOMERCODE_SECRET
    FROM KOPO_CUSTOMERDATA;
    
SELECT LPAD(CUSTOMERCODE, 10, '0'), SUBSTR(CUSTOMERCODE, -4) FROM KOPO_CUSTOMERDATA;

