SELECT A.REGIONID,
    A.REGIONNAME,
    A.AP1ID,
    A.AP1NAME,
    A.ACCOUNTID,
    A.ACCOUNTNAME,
    A.SALESID,
    A.SALESNAME,
    A.PRODUCTGROUP,
    A.PRODUCT,
    (SELECT B.PRODUCT_NAME
        FROM KOPO_PRODUCT_MST B
        WHERE 1=1
        AND A.PRODUCT = B.PRODUCT_ID) AS PRODUCT_NAME,
    A.ITEM,
    A.YEARWEEK,
    A.YEAR,
    A.WEEK,
    A.QTY,
    A.TARGET,
    A.IDX
FROM
KOPO_CHANNEL_RESULT_A01 A;


SELECT A.REGIONID,
    A.REGIONNAME,
    A.AP1ID,
    A.AP1NAME,
    A.ACCOUNTID,
    A.ACCOUNTNAME,
    A.SALESID,
    A.SALESNAME,
    A.PRODUCTGROUP,
    A.PRODUCT,
    B.PRODUCT_NAME,
    A.ITEM,
    A.YEARWEEK,
    A.YEAR,
    A.WEEK,
    A.QTY,
    A.TARGET,
    A.IDX 
FROM 
KOPO_CHANNEL_RESULT_A01 A,
KOPO_PRODUCT_MST B
WHERE 1=1
AND A.PRODUCT = B.PRODUCT_ID(+);