SELECT * FROM KOPO_STUDENT_2018;

SELECT
    TEAM_ID
    , ROUND(AVG(SCORE_MATH),1)
    FROM KOPO_STUDENT_2018
    GROUP BY TEAM_ID;
    
SELECT
    A.STUDENT_ID
    ,A.TEAM_ID
    ,A.SCORE_MATH
    ,B.AVG_MATH
    FROM
        KOPO_STUDENT_2018 A,
        (SELECT
            TEAM_ID
            , ROUND(AVG(SCORE_MATH),1) AS AVG_MATH
            FROM KOPO_STUDENT_2018
            GROUP BY TEAM_ID) B
    WHERE 1=1
        AND A.TEAM_ID = B.TEAM_ID(+);