SELECT * FROM KOPO_CHANNEL_SEASONALITY_NEW;

-- GROUP BY

SELECT REGIONID
        ,PRODUCT
        ,SUM(QTY)
    FROM KOPO_CHANNEL_SEASONALITY_NEW
    GROUP BY REGIONID, PRODUCT
    ORDER BY REGIONID, PRODUCT;

-- GROUP BY ROLLUP

SELECT REGIONID
    ,PRODUCT
    ,SUM(QTY)
FROM KOPO_CHANNEL_SEASONALITY_NEW
GROUP BY ROLLUP(REGIONID, PRODUCT)
ORDER BY REGIONID, PRODUCT;

-- GROUP BY GROUPING SETS

SELECT REGIONID
    ,PRODUCT
    ,SUM(QTY)
FROM KOPO_CHANNEL_SEASONALITY_NEW
GROUP BY GROUPING SETS(REGIONID, PRODUCT, (REGIONID, PRODUCT), ())
ORDER BY REGIONID, PRODUCT;

-- GROUP BY CUBE

SELECT REGIONID
    ,PRODUCT
    ,SUM(QTY)
FROM KOPO_CHANNEL_SEASONALITY_NEW
GROUP BY CUBE(REGIONID, PRODUCT)
ORDER BY REGIONID, PRODUCT;