
---- 109번 문제: CUBE, GROUPING SETS ----

CREATE TABLE EQIP (
    EQIPID VARCHAR2(10),
    EQIPNAME VARCHAR2(10)
    );

CREATE TABLE ENERGY (
    EQUIPID VARCHAR2(10),
    ENGCOCE VARCHAR2(10),
    AMOUNT NUMBER(10)
    );

EDIT EQIP;

EDIT ENERGY;

SELECT * FROM EQIP;

SELECT * FROM ENERGY;

-- 1번 보기
SELECT A.EQIPID, B.ENGCOCE, SUM(B.AMOUNT) AS AMOUNT_SUM
    FROM EQIP A INNER JOIN ENERGY B
    ON (A.EQIPID = B.EQUIPID)
    GROUP BY CUBE (A.EQIPID, B.ENGCOCE, (A.EQIPID, B.ENGCOCE))
    ORDER BY A.EQIPID, B.ENGCOCE;

-- 2번 보기
SELECT A.EQIPID, B.ENGCOCE, SUM(B.AMOUNT) AS AMOUNT_SUM
    FROM EQIP A INNER JOIN ENERGY B
    ON (A.EQIPID = B.EQUIPID)
    GROUP BY CUBE (A.EQIPID, B.ENGCOCE)
    ORDER BY A.EQIPID, B.ENGCOCE;
    
-- 3번 보기
SELECT A.EQIPID, B.ENGCOCE, SUM(B.AMOUNT) AS AMOUNT_SUM
    FROM EQIP A INNER JOIN ENERGY B
    ON (A.EQIPID = B.EQUIPID)
    GROUP BY GROUPING SETS (A.EQIPID, B.ENGCOCE, (A.EQIPID, B.ENGCOCE), ())
    ORDER BY A.EQIPID, B.ENGCOCE;

-- 4번 보기
SELECT A.EQIPID, B.ENGCOCE, SUM(B.AMOUNT) AS AMOUNT_SUM
    FROM EQIP A INNER JOIN ENERGY B
    ON (A.EQIPID = B.EQUIPID)
    GROUP BY GROUPING SETS (A.EQIPID, B.ENGCOCE, (A.EQIPID, B.ENGCOCE))
    ORDER BY A.EQIPID, B.ENGCOCE;

SELECT * FROM TABS;

SELECT * FROM KOPO_TEST_RESULT;

SELECT REGIONID
        ,SUM(VOLUME)
    FROM KOPO_TEST_RESULT
    GROUP BY REGIONID;