SELECT
    C.REGIONID
    ,C.PRODUCT
    ,SUBSTR(C.YEARWEEK,5,2) AS WEEK
    ,ROUND(AVG(C.RATIO),2) AS AVG_RATIO
    FROM(
        SELECT B.*
        ,ROUND(CASE WHEN B.AVG_QTY = 0 THEN 1
        ELSE B.QTY/B.AVG_QTY END, 2) AS RATIO
        FROM(
            SELECT A.*
            ,ROUND(AVG(A.QTY) OVER(PARTITION BY A.REGIONID, A.PRODUCT),2) AS AVG_QTY
            FROM KOPO_CHANNEL_SEASONALITY A
            WHERE 1=1
            AND SUBSTR(A.YEARWEEK,1,4) >= 2015
            AND SUBSTR(A.YEARWEEK,5,2) != 53
            AND A.PRODUCT IN ('PRODUCT1', 'PRODUCT2')
        )B
    )C
    GROUP BY C.REGIONID, C.PRODUCT, SUBSTR(C.YEARWEEK,5,2);