-- PIVOT 예시 #1

SELECT * FROM DT_RESULT_FINAL2
ORDER BY PRODUCTGROUP, PRODUCT, ITEM, YEARWEEK, MEASURE;


SELECT 
    *
     FROM (
        SELECT  *
        FROM DT_RESULT_FINAL2
)
PIVOT( 
    SUM(SALES)
    FOR MEASURE IN 
   ('REAL-QTY' AS REAL_QTY,'PREDICTION-QTY' AS PREDICTION_QTY)
)
ORDER BY PRODUCTGROUP, PRODUCT, ITEM, YEARWEEK;


-- PIVOT 예시 #2

SELECT *
    FROM KOPO_CHANNEL_SEASONALITY_NEW;


SELECT REGIONID
        ,PRODUCT
        ,SUBSTR(YEARWEEK,5,6) AS WEEK
        ,ROUND(AVG(QTY),0) AS AVG_QTY
    FROM KOPO_CHANNEL_SEASONALITY_NEW
    GROUP BY REGIONID, PRODUCT, SUBSTR(YEARWEEK,5,6)
    ORDER BY REGIONID, PRODUCT, SUBSTR(YEARWEEK,5,6);


SELECT *
    FROM (
        SELECT
            REGIONID
            ,PRODUCT
            ,SUBSTR(YEARWEEK,5,6) AS WEEK
            ,ROUND(AVG(QTY),0) AS AVG_QTY
        FROM KOPO_CHANNEL_SEASONALITY_NEW
    GROUP BY REGIONID, PRODUCT, SUBSTR(YEARWEEK,5,6)
    ORDER BY REGIONID, PRODUCT, SUBSTR(YEARWEEK,5,6)
    )
    PIVOT (
    SUM(AVG_QTY)
    FOR WEEK IN ('01' W01, '02' W02, '03' W03, '04' W04, '05' W05, '06' W06)
    )
    ORDER BY REGIONID, PRODUCT;


-- 실습 예제 (P. 60)
-- KOPO_CHANNEL_SEASONALITY_NEW 테이블을 지역/상품별로 평균판매량을 소수점없이
-- 나타내고 W01~W53을 그림과 같은 PIVOT 형태로 표현하세요

SELECT *
    FROM (
    SELECT
        REGIONID
        ,PRODUCT
        ,CONCAT('W', SUBSTR(YEARWEEK,5,6)) AS WEEK
        ,ROUND(AVG(QTY),0) AS AVG_QTY
    FROM KOPO_CHANNEL_SEASONALITY_NEW
    GROUP BY REGIONID, PRODUCT, SUBSTR(YEARWEEK,5,6)
    )
PIVOT( 
    SUM(AVG_QTY)
    FOR WEEK
    IN ('W01' W01, 'W02' W02, 'W03' W03, 'W52' W52, 'W53' W53)
)
ORDER BY REGIONID, PRODUCT;


-- UNPIVOT 예시 #1

SELECT * FROM DT_RESULT_FINAL3;


WITH T AS( 
    SELECT * FROM DT_RESULT_FINAL3
)
SELECT * FROM T
UNPIVOT(QTY FOR MEASURE IN(REAL_QTY, PREDICTION_QTY));


SELECT * FROM DT_RESULT_FINAL3
UNPIVOT(QTY FOR MEASURE IN(REAL_QTY, PREDICTION_QTY));



